language: python
python:
- '2.7'
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libgeos-c1
    - libhdf5-serial-dev
    - libatlas-base-dev
    - gfortran
    - libnetcdf-dev
    - libblas3gf
    - libc6
    - libgcc1
    - libgfortran3
    - liblapack3gf
    - libumfpack5.4.0
    - libstdc++6
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- deps='pip numpy scipy matplotlib basemap shapely nose coverage'
- conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
- export PATH=$HOME/py/bin:$PATH
- pip install pycurl
- pip -v install -r requirements.txt
- pip install coveralls
script:
- python installer/setup.py build_ext -i
- nosetests -v --with-coverage
after_success: coveralls
notifications:
  slack:
    secure: Ckmwy59ytS1GPRZ5Tmvzad6+W9AzvfjNJAa4orgdKS/WktoK4b9W2rbTHxi8V3hBLIDUCso8vIQi3rVXpWY3cFMvb/uRbXO4GiIW1iua3CKjxd+dEw4E6/8DEknS1qdGJRDhN9/3ucZNvSGHY3EQQDfxb/R+OGd2jT6+jed8pss=
